# fly.toml app configuration file generated for aiagentgrocerylist on 2025-04-29T10:39:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aiagentgrocerylist'
primary_region = 'fra'

[build]
    builder = 'flyio/builder'

[env]
  PORT = '8080'

[processes]
  app = "python mainbot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
